<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <PublishAotUsingRuntimePack>true</PublishAotUsingRuntimePack>
    <SelfContained>true</SelfContained>
    <NativeLib>Static</NativeLib>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>false</StripSymbols>
    <PublishTrimmed>true</PublishTrimmed>
    <IsTrimmable>false</IsTrimmable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AssetToolsBridge.Managed\AssetToolsBridge.Managed.csproj" />
  </ItemGroup>
</Project>
